function [fitresult, gof] = createFit1(axisData, curve_fitted_data)
%CREATEFIT1(AXISDATA,CURVE_FITTED_DATA)
%  Create a fit.
%
%  Data for 'CurveFitting' fit:
%      X Input : axisData
%      Y Output: curve_fitted_data
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 26-Feb-2015 11:03:35


%% Fit: 'CurveFitting'.
[xData, yData] = prepareCurveData( axisData, curve_fitted_data );

% Set up fittype and options.
ft = fittype( 'fourier3' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0 0 0 0 0 0 0 0.0128141100758251];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'CurveFitting' );
h = plot( fitresult, xData, yData );
legend( h, 'curve_fitted_data vs. axisData', 'CurveFitting', 'Location', 'NorthEast' );
% Label axes
xlabel( 'axisData' );
ylabel( 'curve_fitted_data' );
grid on


