function [fitresult, gof] = createFit(curve_fitted_data)
%CREATEFIT(CURVE_FITTED_DATA)
%  Create a fit.
%
%  Data for 'CurveFitting' fit:
%      Y Output: curve_fitted_data
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 25-Feb-2015 17:17:47


%% Fit: 'CurveFitting'.
[xData, yData] = prepareCurveData( [], curve_fitted_data );

% Set up fittype and options.
ft = fittype( 'fourier3' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Normalize = 'on';
opts.StartPoint = [0 0 0 0 0 0 0 5.44694645111237];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'CurveFitting' );
h = plot( fitresult, xData, yData );
legend( h, 'curve_fitted_data', 'CurveFitting', 'Location', 'NorthEast' );
% Label axes
ylabel( 'curve_fitted_data' );
grid on


